Attribute VB_Name = "EnumModule"
Public Enum E_JAKI_OPERTOR
    E_EQUAL = 1
    E_NOT_EQUAL
    E_LIKE
    E_NOT_LIKE
    E_ZA_OPERATOR
    E_FLAG_OPERATOR
    E_CGH_LOGIC
    E_RECV_OPERATOR
    E_FLAG_OPERATOR_OSEA
    E_FLAG_OPERATOR_OSEA_F
End Enum


Public Enum E_INPUT_LIST
    INPUT_PLT = 1
    INPUT_PN
    INPUT_DUNS
    INPUT_A
    INPUT_CONT_NUM
    INPUT_DATE_ADDED
    INPUT_EFF
    INPUT_EXP
    INPUT_DESC
    INPUT_SUPPLIER_NM
    INPUT_BYR_CODE
End Enum


Public Enum E_W_GENERAL_LABELS

    FupCode = 1
    PlantCode
    PartNumber
    PartNAME
    BeginningOnHandQty
    DOHQty
    TotalBankQty
    PartHourlyBankQty
    PlantLocMinimumOnHandQty
    MNPC
    Alloc
    OverShort
    dunsNumber
    SUPPLIERNAME
    SupplierCountryCode
    SUPPLIERState
    PrimeDUNSNumber
    TotalYTDReceived
    YTDProduced
    Day1Date
    Day1Req
    Day2Req
    Day3Req
    Day4Req
    Day5Req
    Day6Req
    Day7Req
    Day8Req
    Day9Req
    Day10Req
    Day11Req
    Day12Req
    Day13Req
    Day14Req
    Day15Req
    Day16Req
    Day17Req
    Day18Req
    Day19Req
    Day20Req
    Day21Req
    Day22Req
    Day23Req
    Day24Req
    Day25Req
    Day26Req
    Day27Req
    Day28Req
    Day29Req
    Day30Req
    Day31Req
    Day32Req
    Day33Req
    Day34Req
    Day35Req
    Day36Req
    Day37Req
    Day38Req
    Day39Req
    Day40Req
    Day41Req
    Day42Req
    SupplierStdPack
    SchedulePackDescription
    PartStdPack
    UnitWeight
    ContrNbr
    ContL
    ContW
    ContH
    PrimryContnrWgtMsr
    GrsWgt1StdCont
    InProcessQty
    PlantDeltaQty
    PiecesToGo
    ASLQty
    PlantReworkCurrentPeices
    TotalAdjustment
    SpotBuy
    PrimeCarrierCode
    CarrierTransitTime
    CarrierTransitCode
    DeliveryTimeCode
    ShipTmCd
    BuyerCode
    ReceivingType
    CiscoTransportMode
    DockCode
    DelvLoc
    PRIMULOC
    NewObsoleteCarryOverTp
    CurrSchedTp
    DeactivFlag
    ObsoletePartFlag
    StockKeeper
    NewPartNumber
    KANBANNumber
    DailyComCode1
    DailyComCode2
    DailyComCode3
    PlanComCode1
    PlanComCode2
    PlanComCode3
    PhysCntTxt
    OfficeCmnt
    FloorCmnt
    AField
    ShipmnIdentNbr1
    RecvngStatusTp1
    EstdArrivlDt1
    EstdArrivlTm1
    AsnQty1
    DAV1
    AsnTralrNbr1
    ShipmnComntTxt1
    ShipmnIdentNbr2
    RecvngStatusTp2
    EstdArrivlDt2
    EstdArrivlTm2
    AsnQty2
    DAV2
    AsnTralrNbr2
    ShipmnComntTxt2
    ShipmnIdentNbr3
    RecvngStatusTp3
    EstdArrivlDt3
    EstdArrivlTm3
    AsnQty3
    DAV3
    AsnTralrNbr3
    ShipmnComntTxt3
    ShipmnIdentNbr4
    RecvngStatusTp4
    EstdArrivlDt4
    EstdArrivlTm4
    AsnQty4
    DAV4
    AsnTralrNbr4
    ShipmnComntTxt4
    ShipmnIdentNbr5
    RecvngStatusTp5
    EstdArrivlDt5
    EstdArrivlTm5
    AsnQty5
    DAV5
    AsnTralrNbr5
    ShipmnComntTxt5
    ShipmnIdentNbr6
    RecvngStatusTp6
    EstdArrivlDt6
    EstdArrivlTm6
    AsnQty6
    DAV6
    AsnTralrNbr6
    ShipmnComntTxt6
    ShipmnIdentNbr7
    RecvngStatusTp7
    EstdArrivlDt7
    EstdArrivlTm7
    AsnQty7
    DAV7
    AsnTralrNbr7
    ShipmnComntTxt7
    ShipmnIdentNbr8
    RecvngStatusTp8
    EstdArrivlDt8
    EstdArrivlTm8
    AsnQty8
    DAV8
    AsnTralrNbr8
    ShipmnComntTxt8
    ShipmnIdentNbr9
    RecvngStatusTp9
    EstdArrivlDt9
    EstdArrivlTm9
    AsnQty9
    DAV9
    AsnTralrNbr9
    ShipmnComntTxt9
    ShipmnIdentNbr10
    RecvngStatusTp10
    EstdArrivlDt10
    EstdArrivlTm10
    AsnQty10
    DAV10
    AsnTralrNbr10
    ShipmnComntTxt10
    ShipmnIdentNbr11
    RecvngStatusTp11
    EstdArrivlDt11
    EstdArrivlTm11
    AsnQty11
    DAV11
    AsnTralrNbr11
    ShipmnComntTxt11
    ShipmnIdentNbr12
    RecvngStatusTp12
    EstdArrivlDt12
    EstdArrivlTm12
    AsnQty12
    DAV12
    AsnTralrNbr12
    ShipmnComntTxt12
    FutAsnQty
    ALLDAV
End Enum

