Attribute VB_Name = "EnumModule"
Public Enum E_JAKI_OPERTOR
    E_EQUAL = 1
    E_NOT_EQUAL
    E_LIKE
    E_NOT_LIKE
    E_ZA_OPERATOR
    E_FLAG_OPERATOR
    E_CGH_LOGIC
    E_RECV_OPERATOR
    E_FLAG_OPERATOR_OSEA
    E_FLAG_OPERATOR_OSEA_F
End Enum


Public Enum E_INPUT_LIST
    INPUT_PLT = 1
    INPUT_PN
    INPUT_DUNS
    INPUT_A
    INPUT_CONT_NUM
    INPUT_DATE_ADDED
    INPUT_EFF
    INPUT_EXP
    INPUT_DESC
    INPUT_SUPPLIER_NM
    INPUT_BYR_CODE
End Enum

